apiVersion: apps/v1
kind: Deployment
metadata:
  name: our-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: our-app
  template:
    metadata:
      labels:
        app: our-app
    spec:
      containers:
      - name: frontend
        image: docker.io/ahmedtamer29/frontend:latest
        ports:
        - containerPort: 4000

      - name: product-catalog
        image: docker.io/ahmedtamer29/catalog:latest
        ports:
        - containerPort: 8080

      - name: cart
        image: docker.io/ahmedtamer29/cart:latest
        ports:
        - containerPort: 3000

      - name: auth-service
        image: docker.io/ahmedtamer29/auth:latest
        ports:
        - containerPort: 5000